fix: check error when copying common types

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,12 +5,17 @@ mkdir -p client/src/types
 
 # Copy type definitions in both server and client
 cp -r shared/types/* server/src/types/
-cp -r shared/types/* client/src/types/
-
 if [ $? -ne 0 ]; then
-  echo "Error copying types!"
+  echo "Error copying types in server!"
   exit 1
 fi
+
+cp -r shared/types/* client/src/types/
+if [ $? -ne 0 ]; then
+  echo "Error copying types in client!"
+  exit 1
+fi
+
 git add client/src/types/index.ts
 
 # Run lint-staged
